name: Fullstack Developer Capstone CI/CD
"on": [push, workflow_dispatch]

jobs:
lint-python:
name: Lint Python Files
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- uses: actions/setup-python@v5
with:
python-version: "3.11"
- name: Install dependencies
run: pip install flake8
- name: Run flake8
run: flake8 server

lint-javascript:
name: Lint JavaScript Files
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- uses: actions/setup-node@v4
with:
node-version: "20"
- name: Install dependencies
working-directory: server/frontend
run: npm install
- name: Install JSHint
run: npm install --global jshint
- name: Run JSHint
working-directory: server/frontend
run: jshint src
